services:
  postgres:
    image: postgres:16
    container_name: api_vendas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: api_de_vendas
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
